// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockved/glitterchain/consumer/consumer.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/any"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// consumer pledge dataset token
type CPDT struct {
	DatasetName string                                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	Amount      github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
}

func (m *CPDT) Reset()         { *m = CPDT{} }
func (m *CPDT) String() string { return proto.CompactTextString(m) }
func (*CPDT) ProtoMessage()    {}
func (*CPDT) Descriptor() ([]byte, []int) {
	return fileDescriptor_62febd0321fd018a, []int{0}
}
func (m *CPDT) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CPDT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CPDT.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CPDT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPDT.Merge(m, src)
}
func (m *CPDT) XXX_Size() int {
	return m.Size()
}
func (m *CPDT) XXX_DiscardUnknown() {
	xxx_messageInfo_CPDT.DiscardUnknown(m)
}

var xxx_messageInfo_CPDT proto.InternalMessageInfo

func (m *CPDT) GetDatasetName() string {
	if m != nil {
		return m.DatasetName
	}
	return ""
}

type Consumer struct {
	ConsumerAddress string  `protobuf:"bytes,1,opt,name=consumer_address,json=consumerAddress,proto3" json:"consumer_address,omitempty"`
	CPDTs           []*CPDT `protobuf:"bytes,2,rep,name=CPDTs,proto3" json:"CPDTs,omitempty" yaml:"cpdts"`
	Description     string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *Consumer) Reset()         { *m = Consumer{} }
func (m *Consumer) String() string { return proto.CompactTextString(m) }
func (*Consumer) ProtoMessage()    {}
func (*Consumer) Descriptor() ([]byte, []int) {
	return fileDescriptor_62febd0321fd018a, []int{1}
}
func (m *Consumer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Consumer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Consumer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Consumer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consumer.Merge(m, src)
}
func (m *Consumer) XXX_Size() int {
	return m.Size()
}
func (m *Consumer) XXX_DiscardUnknown() {
	xxx_messageInfo_Consumer.DiscardUnknown(m)
}

var xxx_messageInfo_Consumer proto.InternalMessageInfo

func (m *Consumer) GetConsumerAddress() string {
	if m != nil {
		return m.ConsumerAddress
	}
	return ""
}

func (m *Consumer) GetCPDTs() []*CPDT {
	if m != nil {
		return m.CPDTs
	}
	return nil
}

func (m *Consumer) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ReleasingCPDT struct {
	ConsumerAddress string                `protobuf:"bytes,1,opt,name=consumer_address,json=consumerAddress,proto3" json:"consumer_address,omitempty" yaml:"consumer_address"`
	DatasetName     string                `protobuf:"bytes,2,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty" yaml:"dataset_name"`
	Entries         []*ReleasingCPDTEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (m *ReleasingCPDT) Reset()         { *m = ReleasingCPDT{} }
func (m *ReleasingCPDT) String() string { return proto.CompactTextString(m) }
func (*ReleasingCPDT) ProtoMessage()    {}
func (*ReleasingCPDT) Descriptor() ([]byte, []int) {
	return fileDescriptor_62febd0321fd018a, []int{2}
}
func (m *ReleasingCPDT) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReleasingCPDT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReleasingCPDT.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReleasingCPDT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasingCPDT.Merge(m, src)
}
func (m *ReleasingCPDT) XXX_Size() int {
	return m.Size()
}
func (m *ReleasingCPDT) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasingCPDT.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasingCPDT proto.InternalMessageInfo

func (m *ReleasingCPDT) GetConsumerAddress() string {
	if m != nil {
		return m.ConsumerAddress
	}
	return ""
}

func (m *ReleasingCPDT) GetDatasetName() string {
	if m != nil {
		return m.DatasetName
	}
	return ""
}

func (m *ReleasingCPDT) GetEntries() []*ReleasingCPDTEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ReleasingCPDTs struct {
	RCPDTs []ReleasingCPDT `protobuf:"bytes,1,rep,name=rCPDTs,proto3" json:"rCPDTs"`
}

func (m *ReleasingCPDTs) Reset()         { *m = ReleasingCPDTs{} }
func (m *ReleasingCPDTs) String() string { return proto.CompactTextString(m) }
func (*ReleasingCPDTs) ProtoMessage()    {}
func (*ReleasingCPDTs) Descriptor() ([]byte, []int) {
	return fileDescriptor_62febd0321fd018a, []int{3}
}
func (m *ReleasingCPDTs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReleasingCPDTs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReleasingCPDTs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReleasingCPDTs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasingCPDTs.Merge(m, src)
}
func (m *ReleasingCPDTs) XXX_Size() int {
	return m.Size()
}
func (m *ReleasingCPDTs) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasingCPDTs.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasingCPDTs proto.InternalMessageInfo

func (m *ReleasingCPDTs) GetRCPDTs() []ReleasingCPDT {
	if m != nil {
		return m.RCPDTs
	}
	return nil
}

type ReleasingCPDTEntry struct {
	CreationHeight int64                                  `protobuf:"varint,1,opt,name=creationHeight,proto3" json:"creationHeight,omitempty" yaml:"creation_height"`
	CompletionTime time.Time                              `protobuf:"bytes,2,opt,name=completionTime,proto3,stdtime" json:"completionTime" yaml:"completion_time"`
	Amount         github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
}

func (m *ReleasingCPDTEntry) Reset()         { *m = ReleasingCPDTEntry{} }
func (m *ReleasingCPDTEntry) String() string { return proto.CompactTextString(m) }
func (*ReleasingCPDTEntry) ProtoMessage()    {}
func (*ReleasingCPDTEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_62febd0321fd018a, []int{4}
}
func (m *ReleasingCPDTEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReleasingCPDTEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReleasingCPDTEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReleasingCPDTEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasingCPDTEntry.Merge(m, src)
}
func (m *ReleasingCPDTEntry) XXX_Size() int {
	return m.Size()
}
func (m *ReleasingCPDTEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasingCPDTEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasingCPDTEntry proto.InternalMessageInfo

func (m *ReleasingCPDTEntry) GetCreationHeight() int64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *ReleasingCPDTEntry) GetCompletionTime() time.Time {
	if m != nil {
		return m.CompletionTime
	}
	return time.Time{}
}

// *event*
type ReleasingCPDTEvents struct {
	DatasetName     string `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	ConsumerAddress string `protobuf:"bytes,2,opt,name=consumer_address,json=consumerAddress,proto3" json:"consumer_address,omitempty"`
	Coins           string `protobuf:"bytes,3,opt,name=coins,proto3" json:"coins,omitempty"`
}

func (m *ReleasingCPDTEvents) Reset()         { *m = ReleasingCPDTEvents{} }
func (m *ReleasingCPDTEvents) String() string { return proto.CompactTextString(m) }
func (*ReleasingCPDTEvents) ProtoMessage()    {}
func (*ReleasingCPDTEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_62febd0321fd018a, []int{5}
}
func (m *ReleasingCPDTEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReleasingCPDTEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReleasingCPDTEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReleasingCPDTEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasingCPDTEvents.Merge(m, src)
}
func (m *ReleasingCPDTEvents) XXX_Size() int {
	return m.Size()
}
func (m *ReleasingCPDTEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasingCPDTEvents.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasingCPDTEvents proto.InternalMessageInfo

func (m *ReleasingCPDTEvents) GetDatasetName() string {
	if m != nil {
		return m.DatasetName
	}
	return ""
}

func (m *ReleasingCPDTEvents) GetConsumerAddress() string {
	if m != nil {
		return m.ConsumerAddress
	}
	return ""
}

func (m *ReleasingCPDTEvents) GetCoins() string {
	if m != nil {
		return m.Coins
	}
	return ""
}

type ReleasingDatasetExpiredEvents struct {
	DatasetName     string `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	ConsumerAddress string `protobuf:"bytes,2,opt,name=consumer_address,json=consumerAddress,proto3" json:"consumer_address,omitempty"`
	Coins           string `protobuf:"bytes,3,opt,name=coins,proto3" json:"coins,omitempty"`
}

func (m *ReleasingDatasetExpiredEvents) Reset()         { *m = ReleasingDatasetExpiredEvents{} }
func (m *ReleasingDatasetExpiredEvents) String() string { return proto.CompactTextString(m) }
func (*ReleasingDatasetExpiredEvents) ProtoMessage()    {}
func (*ReleasingDatasetExpiredEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_62febd0321fd018a, []int{6}
}
func (m *ReleasingDatasetExpiredEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReleasingDatasetExpiredEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReleasingDatasetExpiredEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReleasingDatasetExpiredEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasingDatasetExpiredEvents.Merge(m, src)
}
func (m *ReleasingDatasetExpiredEvents) XXX_Size() int {
	return m.Size()
}
func (m *ReleasingDatasetExpiredEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasingDatasetExpiredEvents.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasingDatasetExpiredEvents proto.InternalMessageInfo

func (m *ReleasingDatasetExpiredEvents) GetDatasetName() string {
	if m != nil {
		return m.DatasetName
	}
	return ""
}

func (m *ReleasingDatasetExpiredEvents) GetConsumerAddress() string {
	if m != nil {
		return m.ConsumerAddress
	}
	return ""
}

func (m *ReleasingDatasetExpiredEvents) GetCoins() string {
	if m != nil {
		return m.Coins
	}
	return ""
}

func init() {
	proto.RegisterType((*CPDT)(nil), "blockved.glitterchain.consumer.CPDT")
	proto.RegisterType((*Consumer)(nil), "blockved.glitterchain.consumer.Consumer")
	proto.RegisterType((*ReleasingCPDT)(nil), "blockved.glitterchain.consumer.ReleasingCPDT")
	proto.RegisterType((*ReleasingCPDTs)(nil), "blockved.glitterchain.consumer.ReleasingCPDTs")
	proto.RegisterType((*ReleasingCPDTEntry)(nil), "blockved.glitterchain.consumer.ReleasingCPDTEntry")
	proto.RegisterType((*ReleasingCPDTEvents)(nil), "blockved.glitterchain.consumer.ReleasingCPDTEvents")
	proto.RegisterType((*ReleasingDatasetExpiredEvents)(nil), "blockved.glitterchain.consumer.ReleasingDatasetExpiredEvents")
}

func init() {
	proto.RegisterFile("blockved/glitterchain/consumer/consumer.proto", fileDescriptor_62febd0321fd018a)
}

var fileDescriptor_62febd0321fd018a = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4f, 0x6f, 0xd3, 0x3e,
	0x18, 0x6e, 0xda, 0x6d, 0xbf, 0x1f, 0xee, 0x18, 0x28, 0x9b, 0x58, 0x57, 0x44, 0x32, 0x2c, 0x04,
	0xe3, 0xd0, 0x44, 0x1a, 0xb7, 0xdd, 0xc8, 0xfe, 0x08, 0x04, 0x42, 0x28, 0x1a, 0x1c, 0x90, 0x50,
	0xe5, 0x26, 0x5e, 0x6a, 0x2d, 0xb1, 0xa3, 0xd8, 0xdd, 0xe8, 0x99, 0x0b, 0xc7, 0x7d, 0x12, 0x3e,
	0xc7, 0x8e, 0x3b, 0x22, 0x0e, 0x01, 0xba, 0x6f, 0xd0, 0x4f, 0x80, 0x62, 0x3b, 0x55, 0xda, 0x15,
	0x26, 0x84, 0xc4, 0x29, 0xf1, 0xfb, 0x3e, 0xef, 0xbf, 0xc7, 0xef, 0x63, 0xd0, 0xe9, 0xc5, 0x2c,
	0x38, 0x3e, 0xc1, 0xa1, 0x1b, 0xc5, 0x44, 0x08, 0x9c, 0x05, 0x7d, 0x44, 0xa8, 0x1b, 0x30, 0xca,
	0x07, 0x09, 0xce, 0x26, 0x3f, 0x4e, 0x9a, 0x31, 0xc1, 0x4c, 0xab, 0x84, 0x3b, 0x55, 0xb8, 0x53,
	0xa2, 0xda, 0x1b, 0x01, 0xe3, 0x09, 0xe3, 0x5d, 0x89, 0x76, 0xd5, 0x41, 0x85, 0xb6, 0xd7, 0x22,
	0x16, 0x31, 0x65, 0x2f, 0xfe, 0xb4, 0x75, 0x23, 0x62, 0x2c, 0x8a, 0xb1, 0x2b, 0x4f, 0xbd, 0xc1,
	0x91, 0x8b, 0xe8, 0x50, 0xbb, 0xec, 0x59, 0x97, 0x20, 0x09, 0xe6, 0x02, 0x25, 0xa9, 0x02, 0xc0,
	0x53, 0xb0, 0xb0, 0xfb, 0x7a, 0xef, 0xd0, 0x7c, 0x04, 0x96, 0x43, 0x24, 0x10, 0xc7, 0xa2, 0x4b,
	0x51, 0x82, 0x5b, 0xc6, 0xa6, 0xb1, 0x75, 0xc3, 0x5b, 0x38, 0xcf, 0x6d, 0xc3, 0x6f, 0x6a, 0xcf,
	0x2b, 0x94, 0x60, 0xf3, 0x00, 0x2c, 0xa1, 0x84, 0x0d, 0xa8, 0x68, 0xd5, 0x25, 0xc4, 0x39, 0xcf,
	0xed, 0xda, 0xd7, 0xdc, 0x7e, 0x18, 0x11, 0xd1, 0x1f, 0xf4, 0x9c, 0x80, 0x25, 0xba, 0x67, 0xfd,
	0xe9, 0xf0, 0xf0, 0xd8, 0x15, 0xc3, 0x14, 0x73, 0xe7, 0x39, 0x15, 0xbe, 0x8e, 0x86, 0x9f, 0x0d,
	0xf0, 0xff, 0xae, 0x1e, 0xd9, 0x7c, 0x0c, 0x6e, 0x97, 0xe3, 0x77, 0x51, 0x18, 0x66, 0x98, 0x73,
	0xd5, 0x81, 0x7f, 0xab, 0xb4, 0x3f, 0x55, 0x66, 0xf3, 0x0d, 0x58, 0x2c, 0x1a, 0xe6, 0xad, 0xfa,
	0x66, 0x63, 0xab, 0xb9, 0xfd, 0xc0, 0xf9, 0x3d, 0x9b, 0x4e, 0x01, 0xf6, 0x36, 0x46, 0xb9, 0xad,
	0xc2, 0xc6, 0xb9, 0xbd, 0x3c, 0x44, 0x49, 0xbc, 0x03, 0x83, 0x34, 0x14, 0x1c, 0xfa, 0xca, 0x6c,
	0x6e, 0x82, 0x66, 0x88, 0x79, 0x90, 0x91, 0x54, 0x10, 0x46, 0x5b, 0x0d, 0x59, 0xbc, 0x6a, 0x82,
	0x3f, 0x0c, 0x70, 0xd3, 0xc7, 0x31, 0x46, 0x9c, 0xd0, 0x48, 0x72, 0x76, 0xf0, 0xab, 0xae, 0xbd,
	0xbb, 0xe3, 0xdc, 0x5e, 0xd7, 0x65, 0x66, 0x10, 0xf0, 0xea, 0x48, 0x3b, 0x33, 0xdc, 0x2b, 0x62,
	0xd7, 0xc7, 0xb9, 0xbd, 0xaa, 0x72, 0x54, 0xbd, 0x70, 0xfa, 0x3a, 0x5e, 0x82, 0xff, 0x30, 0x15,
	0x19, 0xc1, 0xbc, 0xd5, 0x90, 0x84, 0x6c, 0x5f, 0x47, 0xc8, 0xd4, 0x0c, 0xfb, 0x54, 0x64, 0x43,
	0xbf, 0x4c, 0x01, 0xdf, 0x83, 0x95, 0x29, 0x37, 0x37, 0x5f, 0x80, 0xa5, 0x4c, 0xf1, 0x6d, 0xc8,
	0xf4, 0x9d, 0x3f, 0x4a, 0x2f, 0x17, 0xa8, 0xe6, 0xeb, 0x14, 0xf0, 0x53, 0x1d, 0x98, 0x57, 0xcb,
	0x9b, 0x1e, 0x58, 0x09, 0x32, 0x8c, 0x0a, 0x96, 0x9f, 0x61, 0x12, 0xf5, 0x85, 0x64, 0xb1, 0xe1,
	0xb5, 0xc7, 0xb9, 0x7d, 0x47, 0xb3, 0xa8, 0xfd, 0xdd, 0xbe, 0x04, 0x40, 0x7f, 0x26, 0xc2, 0x3c,
	0x02, 0x2b, 0x01, 0x4b, 0xd2, 0x18, 0x17, 0xb6, 0x43, 0xa2, 0x59, 0x6c, 0x6e, 0xb7, 0x1d, 0xa5,
	0x00, 0xa7, 0x54, 0x80, 0x73, 0x58, 0x2a, 0xc0, 0x83, 0x45, 0x73, 0x95, 0x1a, 0x93, 0xf8, 0x6e,
	0xa1, 0x12, 0x78, 0xf6, 0xcd, 0x36, 0xfc, 0x99, 0xac, 0x95, 0xf5, 0x6f, 0xfc, 0xd5, 0xfa, 0x0f,
	0xc1, 0xea, 0x34, 0x13, 0x27, 0x98, 0x0a, 0x6e, 0xde, 0x9f, 0x27, 0xc3, 0xe9, 0x1b, 0x9f, 0xa7,
	0x95, 0xfa, 0x7c, 0xad, 0xac, 0x81, 0xc5, 0x80, 0x11, 0xca, 0xf5, 0x3a, 0xab, 0x03, 0xfc, 0x68,
	0x80, 0x7b, 0x93, 0xda, 0x7b, 0x2a, 0xf3, 0xfe, 0x87, 0x94, 0x64, 0x38, 0xfc, 0x77, 0x5d, 0x78,
	0xe9, 0xf9, 0xc8, 0x32, 0x2e, 0x46, 0x96, 0xf1, 0x7d, 0x64, 0x19, 0x67, 0x97, 0x56, 0xed, 0xe2,
	0xd2, 0xaa, 0x7d, 0xb9, 0xb4, 0x6a, 0xef, 0xde, 0x56, 0xa8, 0xd4, 0x3b, 0x46, 0xb1, 0x38, 0x65,
	0xd9, 0xb1, 0x2b, 0x77, 0xad, 0x13, 0xe2, 0xb4, 0x74, 0xe8, 0x47, 0xf2, 0x9a, 0x07, 0x58, 0xd2,
	0xdf, 0x5b, 0x92, 0xd8, 0x27, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x01, 0xe4, 0xe1, 0x06, 0xaf,
	0x05, 0x00, 0x00,
}

func (m *CPDT) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPDT) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CPDT) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintConsumer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.DatasetName) > 0 {
		i -= len(m.DatasetName)
		copy(dAtA[i:], m.DatasetName)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.DatasetName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Consumer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Consumer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Consumer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CPDTs) > 0 {
		for iNdEx := len(m.CPDTs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CPDTs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintConsumer(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ConsumerAddress) > 0 {
		i -= len(m.ConsumerAddress)
		copy(dAtA[i:], m.ConsumerAddress)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.ConsumerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReleasingCPDT) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReleasingCPDT) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReleasingCPDT) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintConsumer(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.DatasetName) > 0 {
		i -= len(m.DatasetName)
		copy(dAtA[i:], m.DatasetName)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.DatasetName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ConsumerAddress) > 0 {
		i -= len(m.ConsumerAddress)
		copy(dAtA[i:], m.ConsumerAddress)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.ConsumerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReleasingCPDTs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReleasingCPDTs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReleasingCPDTs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RCPDTs) > 0 {
		for iNdEx := len(m.RCPDTs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RCPDTs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintConsumer(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ReleasingCPDTEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReleasingCPDTEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReleasingCPDTEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintConsumer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CompletionTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CompletionTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintConsumer(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if m.CreationHeight != 0 {
		i = encodeVarintConsumer(dAtA, i, uint64(m.CreationHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReleasingCPDTEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReleasingCPDTEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReleasingCPDTEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Coins) > 0 {
		i -= len(m.Coins)
		copy(dAtA[i:], m.Coins)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.Coins)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConsumerAddress) > 0 {
		i -= len(m.ConsumerAddress)
		copy(dAtA[i:], m.ConsumerAddress)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.ConsumerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DatasetName) > 0 {
		i -= len(m.DatasetName)
		copy(dAtA[i:], m.DatasetName)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.DatasetName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReleasingDatasetExpiredEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReleasingDatasetExpiredEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReleasingDatasetExpiredEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Coins) > 0 {
		i -= len(m.Coins)
		copy(dAtA[i:], m.Coins)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.Coins)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConsumerAddress) > 0 {
		i -= len(m.ConsumerAddress)
		copy(dAtA[i:], m.ConsumerAddress)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.ConsumerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DatasetName) > 0 {
		i -= len(m.DatasetName)
		copy(dAtA[i:], m.DatasetName)
		i = encodeVarintConsumer(dAtA, i, uint64(len(m.DatasetName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConsumer(dAtA []byte, offset int, v uint64) int {
	offset -= sovConsumer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CPDT) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DatasetName)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovConsumer(uint64(l))
	return n
}

func (m *Consumer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConsumerAddress)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	if len(m.CPDTs) > 0 {
		for _, e := range m.CPDTs {
			l = e.Size()
			n += 1 + l + sovConsumer(uint64(l))
		}
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	return n
}

func (m *ReleasingCPDT) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConsumerAddress)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	l = len(m.DatasetName)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovConsumer(uint64(l))
		}
	}
	return n
}

func (m *ReleasingCPDTs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RCPDTs) > 0 {
		for _, e := range m.RCPDTs {
			l = e.Size()
			n += 1 + l + sovConsumer(uint64(l))
		}
	}
	return n
}

func (m *ReleasingCPDTEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreationHeight != 0 {
		n += 1 + sovConsumer(uint64(m.CreationHeight))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CompletionTime)
	n += 1 + l + sovConsumer(uint64(l))
	l = m.Amount.Size()
	n += 1 + l + sovConsumer(uint64(l))
	return n
}

func (m *ReleasingCPDTEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DatasetName)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	l = len(m.ConsumerAddress)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	l = len(m.Coins)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	return n
}

func (m *ReleasingDatasetExpiredEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DatasetName)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	l = len(m.ConsumerAddress)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	l = len(m.Coins)
	if l > 0 {
		n += 1 + l + sovConsumer(uint64(l))
	}
	return n
}

func sovConsumer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConsumer(x uint64) (n int) {
	return sovConsumer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CPDT) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPDT: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPDT: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatasetName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatasetName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Consumer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Consumer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Consumer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPDTs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CPDTs = append(m.CPDTs, &CPDT{})
			if err := m.CPDTs[len(m.CPDTs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReleasingCPDT) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReleasingCPDT: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReleasingCPDT: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatasetName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatasetName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, &ReleasingCPDTEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReleasingCPDTs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReleasingCPDTs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReleasingCPDTs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RCPDTs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RCPDTs = append(m.RCPDTs, ReleasingCPDT{})
			if err := m.RCPDTs[len(m.RCPDTs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReleasingCPDTEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReleasingCPDTEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReleasingCPDTEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeight", wireType)
			}
			m.CreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CompletionTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReleasingCPDTEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReleasingCPDTEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReleasingCPDTEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatasetName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatasetName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReleasingDatasetExpiredEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReleasingDatasetExpiredEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReleasingDatasetExpiredEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatasetName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatasetName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConsumer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConsumer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConsumer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConsumer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConsumer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConsumer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConsumer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConsumer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConsumer = fmt.Errorf("proto: unexpected end of group")
)
