// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockved/glitterchain/consumer/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_ "github.com/golang/protobuf/ptypes/duration"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// unbonding_time is the time duration of unbonding.
	ReleasingCPDTWaitTime time.Duration `protobuf:"bytes,1,opt,name=releasing_cpdt_wait_time,json=releasingCpdtWaitTime,proto3,stdduration" json:"releasing_cpdt_wait_time" yaml:"releasing_cpdt_wait_time"`
	MaxCPDTNumPerConsumer uint32        `protobuf:"varint,2,opt,name=max_cpdt_num_per_consumer,json=maxCpdtNumPerConsumer,proto3" json:"max_cpdt_num_per_consumer,omitempty" yaml:"max_cpdt_num_per_consumer"`
	MaxCPDTEntries        uint32        `protobuf:"varint,3,opt,name=max_cpdt_entries,json=maxCpdtEntries,proto3" json:"max_cpdt_entries,omitempty" yaml:"max_cpdt_entries"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f686fce43a4bbd, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetReleasingCPDTWaitTime() time.Duration {
	if m != nil {
		return m.ReleasingCPDTWaitTime
	}
	return 0
}

func (m *Params) GetMaxCPDTNumPerConsumer() uint32 {
	if m != nil {
		return m.MaxCPDTNumPerConsumer
	}
	return 0
}

func (m *Params) GetMaxCPDTEntries() uint32 {
	if m != nil {
		return m.MaxCPDTEntries
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "blockved.glitterchain.consumer.Params")
}

func init() {
	proto.RegisterFile("blockved/glitterchain/consumer/params.proto", fileDescriptor_55f686fce43a4bbd)
}

var fileDescriptor_55f686fce43a4bbd = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x3d, 0x8b, 0xd4, 0x40,
	0x1c, 0xc6, 0x33, 0xa7, 0x5c, 0x11, 0xf1, 0x90, 0xe0, 0x62, 0xee, 0x8a, 0x99, 0x90, 0xea, 0x40,
	0x2e, 0x01, 0xed, 0x0e, 0x6c, 0x76, 0xd7, 0x52, 0x59, 0xc2, 0xe1, 0x81, 0x4d, 0x98, 0x24, 0x7f,
	0x73, 0xc3, 0x65, 0x32, 0xc3, 0x64, 0xe2, 0xee, 0x7d, 0x0b, 0xcb, 0x2d, 0xfd, 0x38, 0x5b, 0x6e,
	0x69, 0x15, 0x25, 0xfb, 0x0d, 0xb6, 0xb5, 0x91, 0xbc, 0xcc, 0xe2, 0x0b, 0x8b, 0x5d, 0xc2, 0xf3,
	0x7b, 0x9e, 0x5f, 0x08, 0x7f, 0xfb, 0x65, 0x52, 0x88, 0xf4, 0xfe, 0x33, 0x64, 0x61, 0x5e, 0x30,
	0xad, 0x41, 0xa5, 0x77, 0x94, 0x95, 0x61, 0x2a, 0xca, 0xaa, 0xe6, 0xa0, 0x42, 0x49, 0x15, 0xe5,
	0x55, 0x20, 0x95, 0xd0, 0xc2, 0xc1, 0x06, 0x0e, 0x7e, 0x87, 0x03, 0x03, 0x5f, 0x3c, 0xcf, 0x45,
	0x2e, 0x7a, 0x34, 0xec, 0x9e, 0x86, 0xd6, 0x05, 0xce, 0x85, 0xc8, 0x0b, 0x08, 0xfb, 0xb7, 0xa4,
	0xfe, 0x14, 0x66, 0xb5, 0xa2, 0x9a, 0x89, 0x72, 0xcc, 0xbd, 0x7f, 0x72, 0xa8, 0x52, 0xc5, 0xa4,
	0x16, 0x6a, 0x20, 0xfc, 0x9f, 0x27, 0xf6, 0xe9, 0xa2, 0xff, 0x10, 0x67, 0x8d, 0x6c, 0x57, 0x41,
	0x01, 0xb4, 0x62, 0x65, 0x1e, 0xa7, 0x32, 0xd3, 0xf1, 0x92, 0x32, 0x1d, 0x6b, 0xc6, 0xc1, 0x45,
	0x1e, 0xba, 0x7c, 0xf2, 0xea, 0x3c, 0x18, 0x06, 0x03, 0x33, 0x18, 0xcc, 0x47, 0xe1, 0x74, 0xbe,
	0x69, 0x88, 0xd5, 0x36, 0x64, 0x12, 0x99, 0x89, 0xd9, 0x62, 0x7e, 0x73, 0x4b, 0x99, 0xbe, 0x61,
	0x1c, 0xf6, 0x0d, 0x21, 0x0f, 0x94, 0x17, 0xd7, 0xfe, 0x31, 0x83, 0xbf, 0xfe, 0x4e, 0x50, 0x34,
	0x39, 0xc4, 0x33, 0x99, 0x69, 0xd3, 0x76, 0x96, 0xf6, 0x39, 0xa7, 0xab, 0xa1, 0x51, 0xd6, 0x3c,
	0x96, 0xa0, 0x62, 0xf3, 0x6b, 0xdc, 0x13, 0x0f, 0x5d, 0x3e, 0x9d, 0xbe, 0xe9, 0xdc, 0xef, 0xe8,
	0xaa, 0xb3, 0xbe, 0xaf, 0xf9, 0x02, 0xd4, 0x6c, 0x04, 0xf6, 0x0d, 0xf1, 0x06, 0xf7, 0xd1, 0x0d,
	0x3f, 0x9a, 0x70, 0xba, 0xea, 0x94, 0x7f, 0x56, 0x9d, 0x5b, 0xfb, 0xd9, 0xa1, 0x04, 0xa5, 0x56,
	0x0c, 0x2a, 0xf7, 0x51, 0xef, 0xbb, 0x6a, 0x1b, 0x72, 0x36, 0xfa, 0xde, 0x0e, 0xc9, 0xbe, 0x21,
	0x2f, 0xfe, 0x12, 0x8d, 0x1d, 0x3f, 0x3a, 0x1b, 0xf7, 0x47, 0xf4, 0xfa, 0xf1, 0xfa, 0x2b, 0xb1,
	0xa6, 0x72, 0xd3, 0x62, 0xb4, 0x6d, 0x31, 0xfa, 0xd1, 0x62, 0xf4, 0x65, 0x87, 0xad, 0xed, 0x0e,
	0x5b, 0xdf, 0x76, 0xd8, 0xfa, 0xf8, 0x21, 0x67, 0xfa, 0xae, 0x4e, 0x82, 0x54, 0x70, 0x73, 0x3e,
	0x25, 0xe8, 0xa5, 0x50, 0xf7, 0x61, 0x7f, 0x19, 0x57, 0x19, 0x48, 0x13, 0xc4, 0xc3, 0x5d, 0xfc,
	0xe7, 0xdc, 0xf4, 0x83, 0x84, 0x2a, 0x39, 0xed, 0xd9, 0xd7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xf8, 0x9e, 0x84, 0x2b, 0x9d, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxCPDTEntries != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxCPDTEntries))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxCPDTNumPerConsumer != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxCPDTNumPerConsumer))
		i--
		dAtA[i] = 0x10
	}
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.ReleasingCPDTWaitTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.ReleasingCPDTWaitTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.ReleasingCPDTWaitTime)
	n += 1 + l + sovParams(uint64(l))
	if m.MaxCPDTNumPerConsumer != 0 {
		n += 1 + sovParams(uint64(m.MaxCPDTNumPerConsumer))
	}
	if m.MaxCPDTEntries != 0 {
		n += 1 + sovParams(uint64(m.MaxCPDTEntries))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleasingCPDTWaitTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.ReleasingCPDTWaitTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCPDTNumPerConsumer", wireType)
			}
			m.MaxCPDTNumPerConsumer = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCPDTNumPerConsumer |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCPDTEntries", wireType)
			}
			m.MaxCPDTEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCPDTEntries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
